
PLUGIN_ORG=$8000

PLUGIN_OK=1
PLUGIN_RESTORE_SCREEN=2
PLUGIN_RESTORE_BUFFERS=4
PLUGIN_NAVIGATE=8
PLUGIN_STATUS_MESSAGE=16
PLUGIN_DATA_RETURNED=64
PLUGIN_ERROR=128

PLUGIN_NAVIGATE_NEXT=1
PLUGIN_NAVIGATE_PREVIOUS=2
PLUGIN_NAVIGATE_FIRST=3
PLUGIN_NAVIGATE_LAST=4

PLUGIN_FLAGS1_COPY_SETTINGS=1
PLUGIN_FLAGS1_MMC_ONLY=2

PLUGIN_SETTING_OFFSET_TOP_LINE=0
PLUGIN_SETTING_OFFSET_BOTTOM_LINE=1
PLUGIN_SETTING_OFFSET_BORDER=2
PLUGIN_SETTING_OFFSET_FILE=3
PLUGIN_SETTING_OFFSET_DIRECTORY=4
PLUGIN_SETTING_OFFSET_SELECTION=5
PLUGIN_SETTING_OFFSET_DEVICE=6
PLUGIN_SETTING_OFFSET_FLAGS=7
PLUGIN_SETTING_OFFSET_FLAGS2=8
PLUGIN_SETTING_OFFSET_KEY_UP=9
PLUGIN_SETTING_OFFSET_KEY_DOWN=10
PLUGIN_SETTING_OFFSET_KEY_LEFT=11
PLUGIN_SETTING_OFFSET_KEY_RIGHT=12
PLUGIN_SETTING_OFFSET_KEY_SELECT=13

PLUGIN_SETTING_MAX = 14

PLUGIN_STATUS_SCREEN_ADDR = $50e0 + 24	; x, 20, y = bottom line
